backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "images"
public_folder: "/images"

locale: 'zh_Hans'

collections:
  - name: "products"
    label: "产品图片"
    folder: "_products"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "产品名称（中文）", name: "name_zh", widget: "string", hint: "例如：荠菜包"}
      - {label: "产品名称（英文）", name: "name_en", widget: "string", hint: "例如：Shepherd's Purse Bun"}
      - {label: "产品图片", name: "image", widget: "image"}
      - {label: "供应商名称", name: "supplier", widget: "string"}
      - {label: "联系邮箱", name: "email", widget: "string"}
      - {label: "备注", name: "notes", widget: "text", required: false}
